# Generated by Django 5.2.4 on 2025-07-15 07:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technonogies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='tech/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('PY', 'Python'), ('FA', 'FastAPI'), ('DJ', 'Django'), ('SA', 'SQLAlchemy'), ('RE', 'React')], max_length=3)),
            ],
        ),
    ]
