# Generated by Django 5.2.4 on 2025-07-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_alter_technonogies_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='technonogies',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
